---
- name: Install Node-RED packages
  npm: 
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - node-red
    - node-red-contrib-cron
    - node-red-contrib-gpio
    - node-red-contrib-influxdb
    - node-red-contrib-join
    - node-red-node-ping
    - node-red-node-random
    - node-red-node-smooth
    - node-red-node-weather-underground

# - name: Remove unnecessary Node-RED packages
#   npm: 
#     name: "{{ item }}"
#     global: yes
#     state: absent
#   with_items:
#     - node-red-node-serialport
#     - node-red-node-darksky

- name: Copy Node-RED icon
  copy:
    src: node-red-icon.svg
    dest: /usr/share/icons/hicolor/scalable/apps/node-red-icon.svg

- name: Copy Node-RED service script files
  copy:
    src: "{{ item }}"
    dest: /usr/bin/{{ item }}
    mode: +x
  with_items:
    - node-red-start
    - node-red-stop
    - node-red-log

- name: Copy Node-RED service file
  copy:
    src: nodered.service
    dest: /lib/systemd/system/nodered.service

- name: Copy Node-RED service file
  copy:
    src: settings.js
    dest: ~/settings.js

- name: Register Node-RED service
  systemd:
    name: nodered
    daemon_reload: yes
    enabled: yes
    state: started